### ISSUE TITLE
2번째 섹션에 입력 오류

### ISSUE THREAD

**Issue by seairlog** [becho2/whooing-everyday#4]
제 꿈과 희망을 담아 2번째 섹션에 매주 로또당첨 자동입력을 등록해 두었는데 지난 토요일에 입력이 안되었습니다.ㅎㅎ
전송로그에 아무것도 없는 것 확인했고, 후룹에 POST URL 확인해보니 섹션주소는 제대로 입력한 것 같습니다. 

항목도 가져올 수 없는지 여쭤보려 했는데 벌써 되네요... ㅎㅎ 감사합니다.
그럼 등록된 항목 수정도 될까요? 삭제하고 다시 등록하는게 조금 불편합니다.

**Comment by becho2** [comment]
앗!? 지난 토요일에 입력이요? 음... 로그에도 보낸 이력이 안보이네요. 수정배포하고 있는 중이었으면 앱이 꺼져서 안갔을 수도 있긴 합니다. 그 가능성이 가장 높아보이네요ㅠㅠ 수정해서 배포하는동안 앱이 중지되는 문제를 생각을 좀 해봐야겠습니다. 수정을 하더라도 배포는 반복거래입력이 없는 시간대에 정기적으로 배포되게 한다든지..

수정기능은.. 저 스스로도 수정기능 있으면 편하겠다 싶긴 합니다 ㅋㅋ 최대한 빠른 시일 내에 한번 구현해보겠습니다!

**Comment by becho2** [comment]
등록된 거래에 대한 수정기능을 업데이트하였습니다. 다만 아직 수정기능에서는 불러온 항목 중 선택하는 게 아니라 일단 텍스트를 직접입력해서 수정하는 방식으로 만들어두었습니다. 추후 여유가 되면 수정기능도 입력할 때처럼 시간/달력/항목을 실제 후잉에 존재하는 항목 중 선택 기능을 추가하겠습니다.
혹시 또 입력이 안 되는 경우가 생기거나 다른 의견/문의사항 있으시면 추가로 이슈 남겨주세요! 감사합니다!
